import { StyleSheet } from 'react-native';
import { color } from 'react-native-reanimated';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: "center",
      backgroundColor:'#fff',
      width:'100%'
    },
    logoImage:{ 
        width: 162, 
        height: 170,
        marginTop:60
    },
    plusImage:{ 
        width: 121, 
        height: 121,
    },
    InputImage:{ 
        width: 18, 
        height: 13.5,
        marginLeft:30,
        marginRight:15,
    },
    InputImage1:{ 
        width: 12.17, 
        height: 17.72,
        marginLeft:33,
        marginRight:18
    },
    InputImage2:{ 
        width: 18, 
        height: 18,
        marginLeft:32,
        marginRight:15
    },
    logoTxt:{
        fontSize:13,
        color:'#7E7E7E',
        fontFamily:'Poppins-Regular'
    }, 
    forgpwdTxt:{
        fontSize:15,
        color:'#515151',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        marginTop:20,
        marginBottom:20,
        fontFamily:'Poppins-Regular'
    }, 
    AddShopiingTxt:{
        fontSize:19,
        color:'#414041',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        marginTop:20,
        fontFamily:'Poppins-Regular',
        marginBottom:20
    }, 
    CartTitle:{
        position: 'absolute',
        alignSelf:'center',
        top:45,
        fontSize:20,
        color:'#414041',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        fontFamily:'Poppins-Regular',
        fontSize:18
    }, 
    DetailTitle:{
        alignSelf:'center',
        fontSize:20,
        color:'#414041',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        fontFamily:'Poppins-Regular',
        fontSize:18
    }, 
    inputArea:{
        width:'90%',
        marginTop:35,
    },
    inputTxt:{
        fontSize:13,
        color:'#000',
        width:'70%',
        fontFamily:'Poppins-Regular'
    },
    inputItem:{
        flexDirection:'row',
        alignItems:'center',
        height:55,
        borderRadius:27.5,
        borderWidth:1,
        borderColor:'#e9e9e9',
        marginBottom:22,
        width:'100%'
    },
    forgotBtn:{
        alignItems:'flex-end',
        marginTop:-10
    },
    forgotTxt1:{
        fontSize:13,
        color:"#7E7E7E"
    },
    signinBtn:{
        flexDirection:'row',
        alignItems:'center',
        height:52,
        borderRadius:26,
        backgroundColor:'#61D273',
        marginTop:35,
        justifyContent:'center',
        alignItems:'center',
        width:'100%'
    },
    signinTxt1:{
        fontSize:18,
        color:'white',
        fontFamily:'Poppins-Regular'
    }, 
    dontaccountTxt:{
        color:'#bdbdc6',
        fontSize:14,
        marginTop:18,
        textAlign:'center',
        fontFamily:'NunitoSans-Bold'
    },
    signinTxt:{
        fontSize:14,
        color:'#61D273',
        fontFamily:'NunitoSans-Bold'
    },
    forgotTxt:{
        fontSize:14,
        fontWeight:'bold',
        color:'#7E7E7E',
        fontFamily:'Poppins-Regular'
    },
    wantBtn:{
        justifyContent:'center',
        height:55,
        borderRadius:27.5,
        borderWidth:1,
        borderColor:'#e9e9e9',
        marginBottom:22,
        width:'100%',
        alignItems:'center'
    },
    wantTxt:{
        textAlign:'center',
        color:'#515151',
        fontSize:15,
        fontFamily:'Poppins-Regular'
    },
    personImage:{
        width:120,
        height:120,
        borderRadius:60
    },
    productDetailImage:{
        width:316,
        height:214,
        marginTop:30
    },
    productCartImage:{
        width:120,
        height:120,
    },
    productDescription:{
        color:'#1D1C1C', 
        fontSize:16, 
        fontFamily:'Poppins-Regular'
    },
    AddCartBtn:{
        flexDirection:'row',
        alignItems:'center',
        height:39,
        borderRadius:26,
        backgroundColor:'#61D273',
        marginTop:35,
        justifyContent:'center',
        alignItems:'center',
        width:246,
        alignSelf:'center'
    },
    cartItemArea:{
        flexDirection:'row', 
        alignItems:'center', 
        marginTop:30, 
        width:'90%'
    },
    cartImage:{
        borderRadius:5, 
        borderColor:'#61D273', 
        borderWidth:2, 
        marginRight:20
    },
    personImageArea:{
        width:143,
        height:143,
        borderRadius:72.5,
        borderColor:'#61D273',
        borderWidth:2,
        justifyContent:'center',
        alignItems:'center'
    },
    personImageArea1:{
        width:127,
        height:127,
        borderRadius:100,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'green'
    },
    addImage:{
        width:50,
        height:50,
    },
    backImage:{
        width:56,
        height:40
    },
    paymethodAdd:{
        width:20,
        height:20
    },
    backBtn:{
        position:'absolute',
        left:0
    },
    paymethodAddBtn:{
        position:'absolute',
        right:30,
        top:10
    },
    addBtn:{
        position:'absolute',
        bottom:15, 
        right:-18
    },
    personUploadgImage:{
        marginTop:20
    },
    arrowleft:{
        height:15,
        width:9,
        position:'absolute',
        right:35
    },
    uncheckImage:{
        width:16, 
        height:15,
        marginRight:5, 
        marginLeft:10
    },
    termsTxt:{
        fontSize:10,
        color:'#707070',
        fontFamily:'Poppins-Regular'
    },
    termsTxt1:{
        fontSize:10,
        color:'#707070'
    },
    TermsArea:{
        flexDirection:'row',
        alignItems:'center'
    },
    modal:{
        height:400,
        borderTopRightRadius:45,
        borderTopLeftRadius:45,
        justifyContent:'center',
        alignItems:'center'
    },
    closeImage:{
        height:17,
        width:17
    },
    closeBtn:{
        position:'absolute',
        top:30,
        right: 30,
    },
    homeTitle:{
        fontSize:25,
        fontFamily:'Poppins-SemiBold',
        color:'#070707'
    },
    StoreItem:{
        width:'85%',
        marginTop:30,
        alignItems:'center',
        alignSelf:'center'
    },
    StoreItem1:{
        width:'100%',
        marginTop:30,
        alignItems:'center',
        alignSelf:'center',
    },
    storeImage:{
        width:'100%',
        height:115,
        marginTop:15
    },
    productImage:{
        width:93,
        height:124,
    },
    storeDes:{
        width:'100%',
        height:67,
        backgroundColor:'#61D273',
        borderBottomLeftRadius:25,
        borderBottomRightRadius:25,
        justifyContent:'center',
        alignItems:'center'
    },
    storeDes1:{
        width:'100%',
        height:67,
        backgroundColor:'#61D273',
        borderBottomLeftRadius:25,
        borderBottomRightRadius:25,
        justifyContent:'center',
        alignItems:'center',
        marginTop:-10
    },
    desTxt:{
        color:'white',
        fontSize:10,
        fontFamily:'Poppins-Bold'
    },
    desTxt1:{
        color:'#61D273',
        fontSize:10,
        fontFamily:'Poppins-Bold',
        position:'absolute',
        top:10,
        right:7
    },
    countItem:{
        flexDirection:'row',
        width:95,
        height:30,
        backgroundColor:'#f0f0f0',
        justifyContent:'center',
        alignItems:'center',
        marginTop:20        
    },
    cartAccountArea:{
        width:'33.3%',
        justifyContent: 'center',
        alignItems:'center'
    },
    cartAddBtn:{
        color:'#343434',
        fontSize:17
    },
    paymenntArea:{
        marginTop:40,
        width:'85%',
        alignSelf:'center'
    },
    OrderSummeryTxt:{
        fontSize:18,
        fontFamily:'Poppins-SemiBold',
        color:'#505050'
    },
    ContentItem:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:12,
        marginBottom:12
    },
    ItemTxt:{
        color:'#211D18',
        fontFamily:'Poppins-Regular',
        fontSize:14
    },
    orderContent:{
        marginTop:15,
        borderTopWidth:1,
        borderBottomWidth:1,
        borderColor:'#E5E5E5'
    },
    PromoInput:{
        height:43,
        width:'65%',
        borderTopLeftRadius:21.5,
        borderBottomLeftRadius:21.5,
        borderWidth:1,
        borderColor:'#e9e9e9',
        paddingLeft:20,
        fontSize:13,
        fontFamily:'Poppins-Regular',
    },
    CardNumberInput:{
        height:43,
        width:'100%',
        borderRadius:21.5,
        borderWidth:1,
        borderColor:'#e9e9e9',
        paddingLeft:20,
        fontSize:13,
        fontFamily:'Poppins-Regular',
        marginTop:-20
    },
    specialInput:{
        height:43,
        width:'100%',
        borderRadius:15,
        borderWidth:1,
        borderColor:'#e9e9e9',
        paddingLeft:20,
        fontSize:13,
        fontFamily:'Poppins-Regular',
        marginTop:-20,
        height:86
    },
    ApplyBtn:{
        height:43,
        width:'35%',
        backgroundColor:'#61D273',
        borderTopRightRadius:21.5,
        borderBottomRightRadius:21.5,
        justifyContent:'center',
        alignItems:'center'
    },
    applyBtnTxt:{
        color:'white',
        fontFamily:'Poppins-Regular',
        fontSize:14
    }
})

