import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: "center",
      backgroundColor:'#fff',
      width:'100%'
    },
    logoImage:{ 
        width: 162, 
        height: 170,
        marginTop:60
    },
    plusImage:{ 
        width: 121, 
        height: 121,
    },
    InputImage:{ 
        width: 18, 
        height: 13.5,
        marginLeft:30,
        marginRight:15,
    },
    InputImage1:{ 
        width: 12.17, 
        height: 17.72,
        marginLeft:33,
        marginRight:18
    },
    InputImage2:{ 
        width: 18, 
        height: 18,
        marginLeft:32,
        marginRight:15
    },
    logoTxt:{
        fontSize:13,
        color:'#7E7E7E',
        fontFamily:'Poppins-Regular'
    }, 
    forgpwdTxt:{
        fontSize:15,
        color:'#515151',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        marginTop:20,
        marginBottom:20,
        fontFamily:'Poppins-Regular'
    }, 
    AddShopiingTxt:{
        fontSize:19,
        color:'#414041',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        marginTop:20,
        fontFamily:'Poppins-Regular',
        marginBottom:20
    }, 
    CartTitle:{
        position: 'absolute',
        alignSelf:'center',
        top:30,
        fontSize:20,
        color:'#414041',
        textAlign:'center',
        width:'90%',
        lineHeight:25,
        fontFamily:'Poppins-Regular',
        fontSize:18
    }, 
    inputArea:{
        width:'90%',
        marginTop:35,
    },
    inputTxt:{
        fontSize:13,
        color:'#000',
        width:'70%',
        fontFamily:'Poppins-Regular'
    },
    inputItem:{
        flexDirection:'row',
        alignItems:'center',
        height:55,
        borderRadius:27.5,
        borderWidth:1,
        borderColor:'#e9e9e9',
        marginBottom:22,
        width:'100%'
    },
    forgotBtn:{
        alignItems:'flex-end',
        marginTop:-10
    },
    forgotTxt1:{
        fontSize:13,
        color:"#7E7E7E"
    },
    signinBtn:{
        flexDirection:'row',
        alignItems:'center',
        height:52,
        borderRadius:26,
        backgroundColor:'#61D273',
        marginTop:35,
        justifyContent:'center',
        alignItems:'center',
        width:'100%'
    },
    signinTxt1:{
        fontSize:18,
        color:'white',
        fontFamily:'Poppins-Regular'
    }, 
    dontaccountTxt:{
        color:'#bdbdc6',
        fontSize:14,
        marginTop:18,
        textAlign:'center',
        fontFamily:'NunitoSans-Bold'
    },
    signinTxt:{
        fontSize:14,
        color:'#61D273',
        fontFamily:'NunitoSans-Bold'
    },
    forgotTxt:{
        fontSize:14,
        fontWeight:'bold',
        color:'#7E7E7E',
        fontFamily:'Poppins-Regular'
    },
    wantBtn:{
        justifyContent:'center',
        height:55,
        borderRadius:27.5,
        borderWidth:1,
        borderColor:'#e9e9e9',
        marginBottom:22,
        width:'100%',
        alignItems:'center'
    },
    wantTxt:{
        textAlign:'center',
        color:'#515151',
        fontSize:15,
        fontFamily:'Poppins-Regular'
    },
    personImage:{
        width:120,
        height:120,
        borderRadius:60
    },
    personImageArea:{
        width:143,
        height:143,
        borderRadius:72.5,
        borderColor:'#61D273',
        borderWidth:2,
        justifyContent:'center',
        alignItems:'center'
    },
    personImageArea1:{
        width:127,
        height:127,
        borderRadius:100,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'green'
    },
    addImage:{
        width:50,
        height:50,
    },
    backImage:{
        width:56,
        height:40
    },
    backBtn:{
        position:'absolute',
        left:0
    },
    addBtn:{
        position:'absolute',
        bottom:15, 
        right:-18
    },
    personUploadgImage:{
        marginTop:20
    },
    arrowleft:{
        height:15,
        width:9,
        position:'absolute',
        right:35
    },
    uncheckImage:{
        width:16, 
        height:15,
        marginRight:5, 
        marginLeft:10
    },
    termsTxt:{
        fontSize:10,
        color:'#707070',
        fontFamily:'Poppins-Regular'
    },
    termsTxt1:{
        fontSize:10,
        color:'#707070'
    },
    TermsArea:{
        flexDirection:'row',
        alignItems:'center'
    },
    modal:{
        height:400,
        borderTopRightRadius:45,
        borderTopLeftRadius:45,
        justifyContent:'center',
        alignItems:'center'
    },
    closeImage:{
        height:17,
        width:17
    },
    closeBtn:{
        position:'absolute',
        top:30,
        right: 30,
    },
    homeTitle:{
        fontSize:25,
        fontFamily:'Poppins-SemiBold',
        color:'#070707'
    },
    StoreItem:{
        width:'85%',
        marginTop:30,
        alignItems:'center',
        alignSelf:'center'
    },
    StoreItem1:{
        width:'85%',
        marginTop:30,
        alignItems:'center',
        alignSelf:'center',
        backgroundColor:'red',
    },
    storeImage:{
        width:'100%',
        height:115,
        marginTop:15
    },
    storeDes:{
        width:'100%',
        height:67,
        backgroundColor:'#61D273',
        borderBottomLeftRadius:25,
        borderBottomRightRadius:25,
        marginTop:-7,
        justifyContent:'center',
        alignItems:'center'
    },
    desTxt:{
        color:'white',
        fontSize:10,
        fontFamily:'Poppins-Medium'
    }
})

